hlf:
  username: "_hlfUser"
  channelName: "mychannel"
  chaincodeId: "wse-odb"
  affiliation: "org1"
  mspId: "Org1MSP"
  caUrl: "http://localhost:7054"

ftp:
  provdev:
    protocol: "sftp://"
    host: "30.56.92.18"
    basePath: "/middleware/PUB"
    username: "prov_dev"
    password: "ENC(RIznlfEcYaBZg/DDe+zzIWLDK9BhyMyn)"